### ISSUE TITLE
Meetup #4 content

### ISSUE THREAD

**Issue by ErichDonGubler** [utah-rust/utah-rust.github.io#13]
Meetup link: https://www.meetup.com/utahrust/events/253965052/
PR link: https://github.com/utah-rust/utah-rust.github.io/edit/source/events/2018-09-13-meetup-4.md

Ideas:

* "RustConf in Review" -- talk about what was AWESOME about RustConf and your favorite talks. Maybe watch a few and discuss?
* Ed presents on [one of the issues he's opened](https://github.com/utah-rust/utah-rust.github.io/issues?q=is%3Aissue+is%3Aopen+label%3Aidea-presentation+author%3Aepage)

**Comment by epage** [comment]
I'd be willing to present on any of the [issues I opened](https://github.com/utah-rust/utah-rust.github.io/issues?q=is%3Aissue+is%3Aopen+label%3Aidea-presentation+author%3Aepage)

**Comment by beatgammit** [comment]
I'm interested in presenting, but I'm not sure what topics people are interested in. I'll create a few issues and see where that goes.

That being said, how long should a presentation be? It looks like the Meetup is 2h, but I'm guessing a presentation should be shorter than that? Are we talking around 1hr and questions after?

**Comment by ErichDonGubler** [comment]
@epage: We talked about this on Slack, but just on the record here: one presentation that would go well with the theme of the community would be presenting on the RFC process. I don't know how many people are actually aware of the details, and it would definitely encourage people to participate!

@beatgammit: We'd absolutely be interested in hearing you present! That's fine if it only works in October. :)

**Comment by epage** [comment]
I've opened https://github.com/utah-rust/utah-rust.github.io/issues/16

**Comment by ErichDonGubler** [comment]
Actually, my above comment is false -- I still need to create a page and at least post the link to the slides that @epage presented. Whoops!

**Comment by ErichDonGubler** [comment]
Resolved the above -- closing now!
