### ISSUE TITLE
Rust Evolution

### ISSUE THREAD

**Issue by epage** [utah-rust/utah-rust.github.io#6]
Compare how Rust is handling language + tooling evolution compared to other languages

Topics include
- Release cycle
- Editions
- crates.io compatibility

**Comment by epage** [comment]
I think this was effectively covered when we did the Editions, right?

**Comment by ErichDonGubler** [comment]
I believe so. My question is...how do we now handle the lifetime of this issue? Does it go away, since it's been presented? What if there are valuable things for later? Do we care?

**Comment by CleanCut** [comment]
Yes, that was pretty well covered.

I'd vote to close the issue since that topic has been covered. Closed issues are [still accessible later](https://github.com/utah-rust/utah-rust.github.io/issues?q=is%3Aissue+is%3Aclosed) if you ever want to come back to them for any reason.

**Comment by ErichDonGubler** [comment]
Okay, sounds good -- let's close this, then, and if there's an issue we'll figure it out down the road. :)
